# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='cabo',
  syntax='proto3',
  serialized_pb=_b('\n\rservice.proto\x12\x04\x63\x61\x62o\"+\n\x0eGeneralRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"8\n\x0fGeneralResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\"\x93\x02\n\tBroadcast\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.cabo.Broadcast.msgtype\x12\x0b\n\x03seq\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0b\n\x03msg\x18\x04 \x01(\t\"\xb6\x01\n\x07msgtype\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\r\n\tUSER_JOIN\x10\x01\x12\x0e\n\nUSER_LEAVE\x10\x02\x12\x0e\n\nUSER_READY\x10\x03\x12\x0e\n\nGAME_START\x10\x04\x12\x0c\n\x08GAME_END\x10\x05\x12\r\n\tNEW_ROUND\x10\x06\x12\r\n\tROUND_END\x10\x07\x12\x0f\n\x0bPLAYER_TURN\x10\x08\x12\x11\n\rPLAYER_ACTION\x10\t\x12\x0b\n\x07\x46\x41ILURE\x10\x7f\x32\xb6\x01\n\x08\x43\x61\x62oRoom\x12\x39\n\x08Register\x12\x14.cabo.GeneralRequest\x1a\x15.cabo.GeneralResponse\"\x00\x12\x37\n\x06Handle\x12\x14.cabo.GeneralRequest\x1a\x15.cabo.GeneralResponse\"\x00\x12\x36\n\tSubscribe\x12\x14.cabo.GeneralRequest\x1a\x0f.cabo.Broadcast\"\x00\x30\x01\x62\x06proto3')
)



_BROADCAST_MSGTYPE = _descriptor.EnumDescriptor(
  name='msgtype',
  full_name='cabo.Broadcast.msgtype',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER_JOIN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER_LEAVE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER_READY', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_START', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_END', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEW_ROUND', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROUND_END', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAYER_TURN', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAYER_ACTION', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=10, number=127,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=220,
  serialized_end=402,
)
_sym_db.RegisterEnumDescriptor(_BROADCAST_MSGTYPE)


_GENERALREQUEST = _descriptor.Descriptor(
  name='GeneralRequest',
  full_name='cabo.GeneralRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cabo.GeneralRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='cabo.GeneralRequest.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=66,
)


_GENERALRESPONSE = _descriptor.Descriptor(
  name='GeneralResponse',
  full_name='cabo.GeneralResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='cabo.GeneralResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='cabo.GeneralResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='cabo.GeneralResponse.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=124,
)


_BROADCAST = _descriptor.Descriptor(
  name='Broadcast',
  full_name='cabo.Broadcast',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='cabo.Broadcast.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq', full_name='cabo.Broadcast.seq', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='cabo.Broadcast.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='cabo.Broadcast.msg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BROADCAST_MSGTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=402,
)

_BROADCAST.fields_by_name['type'].enum_type = _BROADCAST_MSGTYPE
_BROADCAST_MSGTYPE.containing_type = _BROADCAST
DESCRIPTOR.message_types_by_name['GeneralRequest'] = _GENERALREQUEST
DESCRIPTOR.message_types_by_name['GeneralResponse'] = _GENERALRESPONSE
DESCRIPTOR.message_types_by_name['Broadcast'] = _BROADCAST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeneralRequest = _reflection.GeneratedProtocolMessageType('GeneralRequest', (_message.Message,), dict(
  DESCRIPTOR = _GENERALREQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:cabo.GeneralRequest)
  ))
_sym_db.RegisterMessage(GeneralRequest)

GeneralResponse = _reflection.GeneratedProtocolMessageType('GeneralResponse', (_message.Message,), dict(
  DESCRIPTOR = _GENERALRESPONSE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:cabo.GeneralResponse)
  ))
_sym_db.RegisterMessage(GeneralResponse)

Broadcast = _reflection.GeneratedProtocolMessageType('Broadcast', (_message.Message,), dict(
  DESCRIPTOR = _BROADCAST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:cabo.Broadcast)
  ))
_sym_db.RegisterMessage(Broadcast)



_CABOROOM = _descriptor.ServiceDescriptor(
  name='CaboRoom',
  full_name='cabo.CaboRoom',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=405,
  serialized_end=587,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='cabo.CaboRoom.Register',
    index=0,
    containing_service=None,
    input_type=_GENERALREQUEST,
    output_type=_GENERALRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Handle',
    full_name='cabo.CaboRoom.Handle',
    index=1,
    containing_service=None,
    input_type=_GENERALREQUEST,
    output_type=_GENERALRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='cabo.CaboRoom.Subscribe',
    index=2,
    containing_service=None,
    input_type=_GENERALREQUEST,
    output_type=_BROADCAST,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CABOROOM)

DESCRIPTOR.services_by_name['CaboRoom'] = _CABOROOM

# @@protoc_insertion_point(module_scope)
